### ISSUE TITLE
Create new develop branch (Git Flow)

### ISSUE THREAD

**Issue by greyscaled** [KevinMarley/KevinMarley.github.io#30]
## Description
Currently `master` branch is more like a 'builds' branch, since that's where GitHub pages builds from (think of it like a heroku master or so). All changes to branch `dev` trigger a build/deploy on `master`, which means `dev` is more like a traditional `master`.

Thus the following structure is desired:
- `master` branch (acts as a `builds` or `dist` or `release`)
- `dev` branch (acts as `master`)
- `next` branch - (acts as active `development`)

## Workflow
- branch `next` from `dev`
- new features branch from `next`
- create release branche from `next` (once `next` receives enough progress) for bugs, docs, review and cleanup
- merge release into `dev` + tag this point
- merge release into `next`, then delete release
- any hotfixes come off of `dev`, then merge into `dev` and `next`

## Todo
- [x] create new branch `next`
- [x] update/check branch settings
- [x] update wiki
- [x] verify correct deployments from CI

**Comment by greyscaled** [comment]
Should be good to close. Re-open if CI does something unexpected.
